spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  mail:
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

minio:
  url: ${R2_ENDPOINT}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET}

r2:
  public-url: ${R2_PUBLIC_URL}

notification:
  provider: resend
  admin-email: ${NOTIFICATION_ADMIN_EMAIL:lucas.haddad0799@gmail.com}

store:
  url: ${STORE_URL}

resend:
  api-key: ${RESEND_API_KEY}
  from: onboarding@resend.dev